config/routes.rb
Rails.application.routes.draw do
  resources :qr_codes
  draw :madmin
  resources :blogs
  resources :cats
  resources :posts
  resources :tags
  resources :articles
  resources :arts
  devise_for :users
  resources :lists
  get 'home/index'
  get 'home/mts'
  get 'home/goo'
  get 'home/a'
  get 'home/e'
  get 'home/about'
  get "up" => "rails/health#show", as: :rails_health_check
  # root "posts#index"
  #root "lists#index"
  #root "home#about"
  root "home#index"
  #root "qr_codes#index"
  #root "arts#index"
  #root "cats#index"
  #  namespace :admin do
  #      resources :arts
  #      resources :articles
  #      resources :cats
  #      resources :lists
  #      resources :posts
  #      resources :tags
  #      resources :taggables
  #      resources :blogs
  #      resources :users

  #      root to: "arts#index"
  #    end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggables, dependent: :destroy
  has_many :articles, through: :taggables
  belongs_to :parent, class_name: "Tag", optional: true  #has_many :taggables, dependent: :destroy
  has_many :subordinates, class_name: "Tag",
    foreign_key: "parent_id", :dependent => :destroy

  def to_s
    name
  end
end

app/controllers/madmin/tags_controller.rb
module Madmin
  class TagsController < Madmin::ResourceController
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  def index
    @tags = Tag.all
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tag.destroy!

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_article-show.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="1collapse navbar-collapse flex justify-between items-center" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item1">
          <h6>
            <strong class="block font-medium mb-1">
              <a href="/tags/<%= @taggable.id %>",
              class="nav-link"><%= @taggable.name %></a>
            </strong>
          </h6>
        </li>
        <li class="nav-item">
          <h5>
            <strong class="block font-medium mb-1">
              <a href="/tags/<%= @tags.last.id %>",
              class="nav-link"><%= @tags.last.name %></a>
            </strong>
          </h5>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/tags/_article.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container-fluid">
    <div class="1collapse navbar-collapse flex justify-between items-center" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% @tags.each do |tag| %>
        <li class="nav-item">
          <h6>
            <strong class="block font-medium mb-1">
              <a href="/tags/<%= tag.id %>",
              class="nav-link"><span lang="ba">
                <%= tag.name %></span></a>
            </strong>
          </h6>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tags/_form.html.erb
<%= form_with(model: tag, class: "contents") do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.select :tag_id,
  options_for_select(Tag.all.map { |tag|
     [tag.name, tag.id]}),
     class: 'form-control',
     :prompt => "Select One" %>
  <br />
  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name,
    class: "block shadow rounded-md border border-gray-200
    dark:text-slate-800 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600
    1text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= tag.name %>
  </p>
  <% tags = article.taggables.
  collect{|taggable| taggable.tag} %>

    <% tag.taggables.each do |taggable| %>
      <h2>Article</h2>
      <%= render 'articles/article', article: taggable.article %>
      <%= link_to "Read More", taggable.article %>
      <hr />
    <% end %>

  <% if action_name != "show" %>
    <%= link_to "Show this tag", tag, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this tag", edit_tag_path(tag), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/tags/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <br>
  <h1 class="font-bold text-4xl">Editing tag</h1>

  <%= render "form", tag: @tag %>

  <%= link_to "Show this tag", @tag,
  class: "ml-2 rounded-lg py-2 px-3 bg-gray-100
  1text-white inline-block font-medium" %>
  <%= link_to "Back to tags", tags_path,
  class: "bg-gray-500 ml-1 mt-1 rounded-lg py-2 px-3
  text-white 1bg-gray-100 inline-block font-medium" %>
</div>

app/views/tags/i.html.erb
        <%= form.submit 'Search', class: "px-4 py-2 font-medium
  bg-orange-600 text-neutal-900 rounded flex items-center
  cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0
  focus:ring-orange-100" %>
<%= link_to "Show this tag", @tag,
class: "ml-2 rounded-lg py-3 px-5 bg-gray-100
inline-block font-medium" %>
<%= link_to "Back to tags", tags_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
<div class="flex justify-between items-center">
  <%= link_to 'New tag', new_tag_path,
  class: "rounded-lg py-3 px-4 bg-blue-600
  text-white block font-medium" %>
</div>
<hr />
<%= render 'tags/article' %>
<br />

<%= select_tag "parent_tag",
options_from_collection_for_select(@tags, "id", "name"),
:prompt => "Select a parent tag",
:onchange => "update_substags_div(this.value)",
class:"dark:text-slate-800" %>
<div id="versionsDiv">
</div>

<% if user_signed_in? && admin_signed_in? %>
<%= render @tags %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tags</h1>
    <%= link_to "New tag", new_tag_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

app/views/tags/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <br />
  <div class="flex justify-between items-center">
    <h1 class="dark:text-slate-400 font-bold text-4xl">Tags</h1>
    <% if user_signed_in? %>
    <%= link_to 'New tag', new_tag_path,
    class: "rounded-lg py-3 px-4 bg-blue-600
    text-white block font-medium" %>
    <% end %>
  </div>
  <br />
  <%= form_with(url: tags_path, method: :get,
  data: {turbo_frame: "tags", turbo_action: "advance"}) do |form| %>
      <%= form.label :query, "Search by tag name:",
      class: "block mb-2" %>
      <div class="flex space-x-3">
        <%= form.text_field :query, class: "py-2 px-4 rounded border ring-0
        focus:ring-4 focus:ring-orange-100 focus:shadow-none
        focus:border-orange-500 dark:text-slate-800 focus:outline-none",
        data: {action: "input->search-form#search"} %>

        <%= form.submit 'Search', class: "px-4 py-2 font-medium
        bg-orange-400 text-neutal-900 rounded flex items-center
        cursor-pointer hover:bg-orange-600 focus:ring-4 ring-0
        text-gray-900 hover:text-gray-100 focus:ring-orange-100" %>
      </div>
  <% end %>
  <br />
  <div id="tags" class="min-w-full">
    <table>
      <thead>
        <tr>
          <th></th>
          <th style="width:10px; heigh:auto"></th>
          <th class="margin:10px; padding-left:10px;
          padding-right:10px;"></th>
          <th style="width:10px; heigh:auto"></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
      <% @tags.each do |tag| %>
          <tr>
            <td>
              <h5>
                <strong class="block font-medium mb-1">
                  <a href="/tags/<%= tag.id %>",
                  class="nav-link"><%= tag.name %></a>
                </strong>
              </h5>
            </td>
            <td style="padding-top:10px; padding-right:0px;
            padding-bottom:20px; padding-left:0">
            <td class="vertical-menu">
              <br />
              <ul class="1vertical-menu">
            <% tag.articles.order('created_at DESC').each do |article| %>
              <li class="vertical-menu">
              <a href="/articles/<%= article.id %>",
                class="nav-link">
                <%= truncate(strip_tags(article.title.to_s),
                length:60) %></a>
                <hr />
              </li>
            <% end %>
              </ul>
            </td>
            <td class="" style="width:10px; heigh:auto"></td>
            <td><%= link_to 'Show', tag %></td>
            <% if user_signed_in? %>
            <td style="width:7px; heigh:auto"></td>
            <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if user_signed_in? %>
  <hr />
  <div class="flex justify-between items-center">
    <%= link_to 'New tag', new_tag_path,
    class: "rounded-lg py-3 px-4 bg-blue-600
    text-white block font-medium" %>
  </div>
  <% end %>
  <br />
</div>

app/views/tags/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New tag</h1>

  <%= render "form", tag: @tag %>

  <%= link_to "Back to tags", tags_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tags/sh.html.erb
<div class="row mt-4 clearfix">
<% if user_signed_in? %>
  <%= link_to "Edit this tag", edit_tag_path(@tag),
  class: "bg-green-700 mt-1 rounded-lg py-2 px-3
  text-white 1bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-1">
    <%= button_to "Destroy this tag", tag_path(@tag), method: :delete,
    class: "bg-red-600 mt-1 rounded-lg py-2 px-3
    1bg-gray-100 font-medium" %>
  </div>
<% end %>
<%= link_to "Back to tags", tags_path,
class: "bg-gray-500 ml-1 rounded-lg py-2 px-3
 text-white 1bg-gray-100 inline-block font-medium" %>
<div class="inline-block ml-1">
  <%= link_to "New tag", new_tag_path,
  class: "bg-blue-700 mt-1 rounded-lg py-2 px-3
  1block inline-block font-medium text-white" %>
</div>
<% if user_signed_in? %>
  <%= link_to 'Edit this tag', edit_tag_path(@tag),
  class: "mt-2 rounded-lg py-3 px-4 bg-gray-100
  text-white inline-block font-medium" %>
  <div class="inline-block ml-1">
    <%= button_to "Destroy this art", tag_path(@tag), method: :delete,
    class: "bg-red-600 mt-1 rounded-lg py-2 px-3
    1bg-gray-100 font-medium" %>
  </div>
<% end %>
  <%= link_to "Back to tags", tags_path,
  class: "ml-2 rounded-lg py-3 px-4
  1bg-gray-100 text-white inline-block font-medium" %>
  <div class="inline-block ml-2">
    <br/>
    <%= link_to 'New tag', new_tag_path,
    class: "rounded-lg py-3 px-4 bg-blue-600
    text-white block font-medium" %>
  </div>
<%= render 'tags/artic' %>

app/views/tags/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <br />
    <div class="1flex justify-between items-center">
      <% if user_signed_in? %>
        <%= link_to "Edit this tag", edit_tag_path(@tag),
        class: "bg-green-700 mt-1 rounded-lg py-2 px-3
        text-white 1bg-gray-100 inline-block font-medium" %>
        <div class="inline-block ml-1">
          <%= button_to "Destroy this tag", tag_path(@tag), method: :delete,
          class: "bg-red-600 mt-1 rounded-lg py-2 px-3
          text-white 1bg-gray-100 font-medium" %>
        </div>
      <% end %>
      <%= link_to "Back to tags", tags_path,
      class: "bg-gray-500 ml-1 mt-1 rounded-lg py-2 px-3
      text-white 1bg-gray-100 1inline-block font-medium" %>
      <div class="inline-block ml-1">
        <%= link_to "New tag", new_tag_path,
        class: "bg-blue-700 mt-1 rounded-lg py-2 px-3
        1block inline-block font-medium text-white" %>
      </div>
    </div>
    <br />
    <h3><%= @tag.name %></h3>
    <div>
      <% @tag.articles.each do |n| %>
      <div class="row  mt-4 clearfix">
        <div class="col-8 col-sm-8 col-md-9 col-lg-9">
        <strong class="block font-medium mb-1">
          <a href="/articles/<%= n.id %>",
          class="nav-link"><%= n.title %></a>
        </strong>
        <%= truncate(strip_tags(n.body.to_s), length:120) %>
        </div>
        <div class="col-4 col-sm-4 col-md-3 col-lg-3 clearfix">
        <% if n.image.attached? %>
          <%= link_to image_tag(n.image,
          style:"width:100px; heigh:auto; nav-link; nav-right;"),
          n.image %>
        <% end %>
        </div>
      </div>
      <hr />
      <% end %>
    </div>
    <div class="1flex justify-between items-center">
      <% if user_signed_in? %>
        <%= link_to "Edit this tag", edit_tag_path(@tag),
        class: "bg-green-700 mt-1 rounded-lg py-2 px-3
        text-white 1bg-gray-100 inline-block font-medium" %>
        <div class="inline-block ml-1">
          <%= button_to "Destroy this tag", tag_path(@tag), method: :delete,
          class: "bg-red-600 mt-1 rounded-lg py-2 px-3
          text-white 1bg-gray-100 font-medium" %>
        </div>
      <% end %>
      <%= link_to "Back to tags", tags_path,
      class: "bg-gray-500 ml-1 mt-1 rounded-lg py-2 px-3
      text-white 1bg-gray-100 1inline-block font-medium" %>
      <div class="inline-block ml-1">
        <%= link_to "New tag", new_tag_path,
        class: "bg-blue-700 mt-1 rounded-lg py-2 px-3
        1block inline-block font-medium text-white" %>
      </div>
    </div>
  </div>
</div>